import { Product, Category, Review, User } from '../types'

export const categories: Category[] = [
  { id: '1', name: 'Proteins', slug: 'proteins', description: 'Whey, casein, and plant-based proteins' },
  { id: '2', name: 'Pre-Workout', slug: 'pre-workout', description: 'Energy and focus boosters' },
  { id: '3', name: 'Creatine', slug: 'creatine', description: 'Strength and power supplements' },
  { id: '4', name: 'Vitamins', slug: 'vitamins', description: 'Essential vitamins and minerals' },
  { id: '5', name: 'Amino Acids', slug: 'amino-acids', description: 'BCAAs and EAAs' },
  { id: '6', name: 'Weight Loss', slug: 'weight-loss', description: 'Fat burners and metabolism boosters' },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Premium Whey Protein Isolate',
    slug: 'premium-whey-protein-isolate',
    description: 'Our premium whey protein isolate delivers 25g of high-quality protein per serving. Made from grass-fed cow milk, it\'s perfect for muscle recovery and growth. Available in delicious chocolate and vanilla flavors.',
    price: 54.99,
    salePrice: 44.99,
    imageUrl: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400',
    gallery: [
      'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800',
      'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=800',
    ],
    brand: 'ProForce',
    category: categories[0],
    ingredients: 'Whey Protein Isolate, Natural Flavors, Sunflower Lecithin, Stevia',
    nutrition: { protein: 25, carbs: 3, fat: 1, calories: 120, servingSize: '30g' },
    dosage: 'Mix 1 scoop with 8-10 oz of water or milk',
    certifications: ['GMP Certified', 'Informed Sport', 'Lab Tested'],
    stock: 150,
    rating: 4.8,
    reviewCount: 256,
    isActive: true,
    createdAt: '2026-01-15',
  },
  {
    id: '2',
    name: 'Explosive Pre-Workout Formula',
    slug: 'explosive-pre-workout-formula',
    description: 'Unleash your full potential with our explosive pre-workout formula. Packed with caffeine, beta-alanine, and citrulline for maximum energy, focus, and pumps.',
    price: 39.99,
    imageUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400',
    brand: 'PowerPump',
    category: categories[1],
    ingredients: 'Citrulline Malate, Beta-Alanine, Caffeine Anhydrous, L-Theanine',
    dosage: 'Mix 1 scoop with 10-12 oz water, consume 20-30 min before workout',
    certifications: ['GMP Certified', 'Third Party Tested'],
    stock: 200,
    rating: 4.6,
    reviewCount: 189,
    isActive: true,
    createdAt: '2026-02-01',
  },
  {
    id: '3',
    name: 'Micronized Creatine Monohydrate',
    slug: 'micronized-creatine-monohydrate',
    description: 'Pure micronized creatine monohydrate for enhanced strength, power, and muscle growth. Zero fillers, zero additives - just pure performance.',
    price: 29.99,
    salePrice: 24.99,
    imageUrl: 'https://images.unsplash.com/photo-1579722820338-3e6c7e0e6e6e?w=400',
    brand: 'PureGain',
    category: categories[2],
    ingredients: '100% Micronized Creatine Monohydrate',
    dosage: 'Take 5g daily with water or protein shake',
    certifications: ['Informed Sport', 'Lab Tested', 'Vegan Friendly'],
    stock: 300,
    rating: 4.9,
    reviewCount: 342,
    isActive: true,
    createdAt: '2026-01-20',
  },
  {
    id: '4',
    name: 'Complete Daily Multivitamin',
    slug: 'complete-daily-multivitamin',
    description: 'Comprehensive multivitamin with 25+ essential vitamins and minerals. Support your overall health and fill nutritional gaps in your diet.',
    price: 24.99,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400',
    brand: 'VitaCore',
    category: categories[3],
    ingredients: 'Vitamin A, C, D, E, K, B-Complex, Zinc, Magnesium, Selenium',
    dosage: 'Take 2 tablets daily with food',
    certifications: ['GMP Certified', 'USP Verified'],
    stock: 500,
    rating: 4.7,
    reviewCount: 178,
    isActive: true,
    createdAt: '2026-02-10',
  },
  {
    id: '5',
    name: 'BCAA Energy Recovery Complex',
    slug: 'bcaa-energy-recovery-complex',
    description: '2:1:1 ratio of leucine, isoleucine, and valine with added electrolytes for hydration. Perfect for intra-workout recovery and muscle preservation.',
    price: 34.99,
    imageUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400',
    brand: 'RecoverMax',
    category: categories[4],
    ingredients: 'L-Leucine, L-Isoleucine, L-Valine, Electrolytes, Vitamin B6',
    dosage: 'Mix 1 scoop with 12-16 oz water during workout',
    certifications: ['Informed Sport', 'Lab Tested'],
    stock: 180,
    rating: 4.5,
    reviewCount: 134,
    isActive: true,
    createdAt: '2026-03-01',
  },
  {
    id: '6',
    name: 'Thermo Burn Fat Burner',
    slug: 'thermo-burn-fat-burner',
    description: 'Advanced thermogenic formula to boost metabolism and support fat loss. Contains green tea extract, caffeine, and capsaicin for maximum effectiveness.',
    price: 44.99,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400',
    brand: 'SlimForce',
    category: categories[5],
    ingredients: 'Green Tea Extract, Caffeine, Capsaicin, L-Carnitine, CLA',
    dosage: 'Take 2 capsules in the morning and 1 in the afternoon',
    certifications: ['GMP Certified'],
    stock: 120,
    rating: 4.3,
    reviewCount: 89,
    isActive: true,
    createdAt: '2026-03-15',
  },
]

export const reviews: Review[] = [
  {
    id: '1',
    userId: 'user1',
    user: { id: 'user1', email: 'john@example.com', firstName: 'John', lastName: 'Doe', role: 'user', createdAt: '2026-01-01' },
    productId: '1',
    rating: 5,
    title: 'Best protein I\'ve ever used!',
    comment: 'Amazing taste and mixes perfectly. I\'ve noticed significant muscle recovery improvements since using this product.',
    isVerified: true,
    createdAt: '2026-08-15',
  },
  {
    id: '2',
    userId: 'user2',
    user: { id: 'user2', email: 'sarah@example.com', firstName: 'Sarah', lastName: 'Smith', role: 'user', createdAt: '2026-01-15' },
    productId: '1',
    rating: 4,
    title: 'Great quality, good value',
    comment: 'High quality protein at a reasonable price. Would recommend to anyone looking for a reliable whey isolate.',
    isVerified: true,
    createdAt: '2026-08-20',
  },
]

export const mockUser: User = {
  id: 'user1',
  email: 'alex@example.com',
  firstName: 'Alex',
  lastName: 'Strong',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
  role: 'user',
  createdAt: '2026-01-01',
}
