import { Product, Category, Review, User } from '../types'

export const categories: Category[] = [
  { id: '1', name: 'Proteins', slug: 'proteins', description: 'Whey, casein, and plant-based proteins', imageUrl: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400' },
  { id: '2', name: 'Pre-Workout', slug: 'pre-workout', description: 'Energy and focus boosters', imageUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400' },
  { id: '3', name: 'Creatine', slug: 'creatine', description: 'Strength and power supplements', imageUrl: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400' },
  { id: '4', name: 'Vitamins', slug: 'vitamins', description: 'Essential vitamins and minerals', imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400' },
  { id: '5', name: 'Amino Acids', slug: 'amino-acids', description: 'BCAAs and EAAs', imageUrl: 'https://images.unsplash.com/photo-1579722820338-3e6c7e0e6e6e?w=400' },
  { id: '6', name: 'Weight Loss', slug: 'weight-loss', description: 'Fat burners and metabolism boosters', imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400' },
  { id: '7', name: 'Mass Gainers', slug: 'mass-gainers', description: 'High-calorie muscle building formulas', imageUrl: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400' },
  { id: '8', name: 'Recovery', slug: 'recovery', description: 'Post-workout recovery supplements', imageUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400' },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Premium Whey Protein Isolate',
    slug: 'premium-whey-protein-isolate',
    description: 'Our premium whey protein isolate delivers 25g of high-quality protein per serving. Made from grass-fed cow milk, it\'s perfect for muscle recovery and growth. Available in delicious chocolate and vanilla flavors. Ultra-filtered for maximum protein content and minimal fat/carbs.',
    price: 54.99,
    salePrice: 44.99,
    imageUrl: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&h=400&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800&h=800&fit=crop',
    ],
    brand: 'ProForce',
    category: categories[0],
    ingredients: 'Whey Protein Isolate, Natural Flavors, Sunflower Lecithin, Stevia, Digestive Enzymes',
    nutrition: { protein: 25, carbs: 3, fat: 1, calories: 120, servingSize: '30g' },
    dosage: 'Mix 1 scoop (30g) with 8-10 oz of water or milk. Shake or blend for 30 seconds.',
    certifications: ['GMP Certified', 'Informed Sport', 'Lab Tested'],
    stock: 150,
    rating: 4.8,
    reviewCount: 256,
    isActive: true,
    createdAt: '2026-01-15',
  },
  {
    id: '2',
    name: 'Explosive Pre-Workout Formula',
    slug: 'explosive-pre-workout-formula',
    description: 'Unleash your full potential with our explosive pre-workout formula. Packed with caffeine, beta-alanine, and citrulline for maximum energy, focus, and muscle pumps. Train harder, longer, and with unmatched intensity.',
    price: 39.99,
    salePrice: 34.99,
    imageUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400&h=400&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&h=800&fit=crop',
    ],
    brand: 'PowerPump',
    category: categories[1],
    ingredients: 'Citrulline Malate, Beta-Alanine, Caffeine Anhydrous, L-Theanine, Tyrosine, Electrolytes',
    dosage: 'Mix 1 scoop with 10-12 oz water. Consume 20-30 minutes before workout. Start with half scoop if sensitive to caffeine.',
    certifications: ['GMP Certified', 'Third Party Tested'],
    stock: 200,
    rating: 4.6,
    reviewCount: 189,
    isActive: true,
    createdAt: '2026-02-01',
  },
  {
    id: '3',
    name: 'Micronized Creatine Monohydrate',
    slug: 'micronized-creatine-monohydrate',
    description: 'Pure micronized creatine monohydrate for enhanced strength, power, and muscle growth. Zero fillers, zero additives - just pure performance. Micronized for better absorption and mixing.',
    price: 29.99,
    salePrice: 24.99,
    imageUrl: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400&h=400&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&h=800&fit=crop',
    ],
    brand: 'PureGain',
    category: categories[2],
    ingredients: '100% Micronized Creatine Monohydrate (Creapure)',
    dosage: 'Take 5g daily with water or protein shake. Can be taken anytime, with or without food.',
    certifications: ['Informed Sport', 'Lab Tested', 'Vegan Friendly'],
    stock: 300,
    rating: 4.9,
    reviewCount: 342,
    isActive: true,
    createdAt: '2026-01-20',
  },
  {
    id: '4',
    name: 'Complete Daily Multivitamin',
    slug: 'complete-daily-multivitamin',
    description: 'Comprehensive multivitamin with 25+ essential vitamins and minerals. Support your overall health, boost immunity, and fill nutritional gaps in your diet. Designed specifically for active individuals.',
    price: 24.99,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&h=400&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800&h=800&fit=crop',
    ],
    brand: 'VitaCore',
    category: categories[3],
    ingredients: 'Vitamin A, C, D3, E, K2, B-Complex, Zinc, Magnesium, Selenium, Iron, Copper',
    dosage: 'Take 2 tablets daily with food. Best taken with breakfast for optimal absorption.',
    certifications: ['GMP Certified', 'USP Verified'],
    stock: 500,
    rating: 4.7,
    reviewCount: 178,
    isActive: true,
    createdAt: '2026-02-10',
  },
  {
    id: '5',
    name: 'BCAA Energy Recovery Complex',
    slug: 'bcaa-energy-recovery-complex',
    description: '2:1:1 ratio of leucine, isoleucine, and valine with added electrolytes for hydration. Perfect for intra-workout recovery, muscle preservation, and endurance during long training sessions.',
    price: 34.99,
    salePrice: 29.99,
    imageUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400&h=400&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=800&h=800&fit=crop',
    ],
    brand: 'RecoverMax',
    category: categories[4],
    ingredients: 'L-Leucine, L-Isoleucine, L-Valine, Electrolytes, Vitamin B6, L-Glutamine',
    dosage: 'Mix 1 scoop (10g) with 12-16 oz water. Consume during or after workout.',
    certifications: ['Informed Sport', 'Lab Tested'],
    stock: 180,
    rating: 4.5,
    reviewCount: 134,
    isActive: true,
    createdAt: '2026-03-01',
  },
  {
    id: '6',
    name: 'Thermo Burn Fat Burner',
    slug: 'thermo-burn-fat-burner',
    description: 'Advanced thermogenic formula to boost metabolism and support fat loss. Contains green tea extract, caffeine, and capsaicin for maximum effectiveness. Combined with diet and exercise for best results.',
    price: 44.99,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&h=400&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&h=800&fit=crop',
    ],
    brand: 'SlimForce',
    category: categories[5],
    ingredients: 'Green Tea Extract, Caffeine Anhydrous, Capsaicin, L-Carnitine, CLA, Chromium',
    dosage: 'Take 2 capsules in the morning and 1 in the afternoon. Do not take within 6 hours of sleep.',
    certifications: ['GMP Certified'],
    stock: 120,
    rating: 4.3,
    reviewCount: 89,
    isActive: true,
    createdAt: '2026-03-15',
  },
  {
    id: '7',
    name: 'Mass Gainer Pro 6lbs',
    slug: 'mass-gainer-pro',
    description: 'High-calorie mass gainer with 50g protein and 1,250 calories per serving. Perfect for hard gainers who struggle to consume enough calories. Complex carbs and quality protein for lean mass building.',
    price: 64.99,
    salePrice: 54.99,
    imageUrl: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=400&h=400&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800&h=800&fit=crop',
    ],
    brand: 'BulkUp',
    category: categories[6],
    ingredients: 'Maltodextrin, Whey Protein Concentrate, Creatine Monohydrate, Natural Flavors, MCT Oil',
    nutrition: { protein: 50, carbs: 250, fat: 8, calories: 1250, servingSize: '334g (2 scoops)' },
    dosage: 'Mix 2 scoops with 16 oz water or milk. Take between meals or after workout.',
    certifications: ['GMP Certified', 'Lab Tested'],
    stock: 80,
    rating: 4.4,
    reviewCount: 67,
    isActive: true,
    createdAt: '2026-04-01',
  },
  {
    id: '8',
    name: 'Nighttime Casein Protein',
    slug: 'nighttime-casein-protein',
    description: 'Slow-digesting casein protein for overnight muscle recovery. Provides steady amino acids for up to 7 hours. Perfect before bed to prevent muscle breakdown during sleep.',
    price: 49.99,
    imageUrl: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400&h=400&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=800&h=800&fit=crop',
    ],
    brand: 'NightRecover',
    category: categories[7],
    ingredients: 'Micellar Casein, Natural Flavors, Digestive Enzymes, L-Tryptophan',
    nutrition: { protein: 24, carbs: 4, fat: 1, calories: 120, servingSize: '32g' },
    dosage: 'Mix 1 scoop with 8-10 oz water or milk. Consume 30 minutes before bed.',
    certifications: ['GMP Certified', 'Informed Sport'],
    stock: 100,
    rating: 4.7,
    reviewCount: 92,
    isActive: true,
    createdAt: '2026-04-15',
  },
  {
    id: '9',
    name: 'Electrolyte Hydration Complex',
    slug: 'electrolyte-hydration-complex',
    description: 'Advanced electrolyte formula with 5 essential electrolytes plus coconut water powder. Stay hydrated during intense workouts. Zero sugar, zero calories - just pure hydration.',
    price: 19.99,
    salePrice: 16.99,
    imageUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400&h=400&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&h=800&fit=crop',
    ],
    brand: 'HydroMax',
    category: categories[7],
    ingredients: 'Sodium, Potassium, Magnesium, Calcium, Coconut Water Powder, Trace Minerals',
    dosage: 'Mix 1 scoop with 16 oz water. Consume before, during, or after exercise.',
    certifications: ['Informed Sport', 'Vegan Friendly'],
    stock: 250,
    rating: 4.6,
    reviewCount: 145,
    isActive: true,
    createdAt: '2026-05-01',
  },
  {
    id: '10',
    name: 'Omega-3 Fish Oil',
    slug: 'omega-3-fish-oil',
    description: 'High-potency omega-3 fish oil with 1,000mg EPA/DHA per serving. Supports heart health, joint health, and recovery. Molecularly distilled for purity and no fishy aftertaste.',
    price: 22.99,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&h=400&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=800&h=800&fit=crop',
    ],
    brand: 'OmegaPure',
    category: categories[3],
    ingredients: 'Fish Oil (Anchovy, Sardine), EPA, DHA, Vitamin E, Gelatin Capsule',
    dosage: 'Take 2 softgels daily with food. Best taken with a meal containing fat.',
    certifications: ['IFOS Certified', 'GMP Certified', 'Non-GMO'],
    stock: 400,
    rating: 4.8,
    reviewCount: 203,
    isActive: true,
    createdAt: '2026-05-15',
  },
  {
    id: '11',
    name: 'L-Glutamine Recovery Powder',
    slug: 'l-glutamine-recovery-powder',
    description: 'Pure L-glutamine powder for enhanced recovery, gut health, and immune support. Most abundant amino acid in muscle tissue. Essential for intense training recovery.',
    price: 27.99,
    salePrice: 22.99,
    imageUrl: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400&h=400&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800&h=800&fit=crop',
    ],
    brand: 'GlutaPure',
    category: categories[4],
    ingredients: '100% Pure L-Glutamine (Pharmaceutical Grade)',
    dosage: 'Take 5g (1 teaspoon) post-workout or before bed. Mix with water or juice.',
    certifications: ['GMP Certified', 'Vegan Friendly', 'Lab Tested'],
    stock: 180,
    rating: 4.5,
    reviewCount: 112,
    isActive: true,
    createdAt: '2026-06-01',
  },
  {
    id: '12',
    name: 'Testosterone Booster',
    slug: 'testosterone-booster',
    description: 'Natural testosterone support formula with ashwagandha, zinc, and vitamin D3. Designed to support healthy testosterone levels, libido, and overall male vitality.',
    price: 39.99,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&h=400&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1550572017-edd951b55104?w=800&h=800&fit=crop',
      'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&h=800&fit=crop',
    ],
    brand: 'VitaBoost',
    category: categories[3],
    ingredients: 'Ashwagandha, Zinc, Vitamin D3, Fenugreek, Tribulus, D-Aspartic Acid',
    dosage: 'Take 4 capsules daily with food. Best taken in the morning.',
    certifications: ['GMP Certified', 'Lab Tested'],
    stock: 90,
    rating: 4.2,
    reviewCount: 76,
    isActive: true,
    createdAt: '2026-06-15',
  },
]

export const reviews: Review[] = [
  {
    id: '1',
    userId: 'user1',
    user: { id: 'user1', email: 'john@example.com', firstName: 'John', lastName: 'Doe', role: 'user', createdAt: '2026-01-01' },
    productId: '1',
    rating: 5,
    title: 'Best protein I\'ve ever used!',
    comment: 'Amazing taste and mixes perfectly. I\'ve noticed significant muscle recovery improvements since using this product. The chocolate flavor is incredible and doesn\'t have that artificial aftertaste.',
    isVerified: true,
    createdAt: '2026-08-15',
  },
  {
    id: '2',
    userId: 'user2',
    user: { id: 'user2', email: 'sarah@example.com', firstName: 'Sarah', lastName: 'Smith', role: 'user', createdAt: '2026-01-15' },
    productId: '1',
    rating: 4,
    title: 'Great quality, good value',
    comment: 'High quality protein at a reasonable price. Would recommend to anyone looking for a reliable whey isolate. Mixes well with oat milk for a great post-workout shake.',
    isVerified: true,
    createdAt: '2026-08-20',
  },
  {
    id: '3',
    userId: 'user3',
    user: { id: 'user3', email: 'mike@example.com', firstName: 'Mike', lastName: 'Johnson', role: 'user', createdAt: '2026-02-01' },
    productId: '2',
    rating: 5,
    title: 'Incredible energy boost!',
    comment: 'This pre-workout gives me the perfect amount of energy without the jitters. The pumps are insane and I can push through my last few reps with ease. Best pre-workout on the market.',
    isVerified: true,
    createdAt: '2026-08-18',
  },
  {
    id: '4',
    userId: 'user4',
    user: { id: 'user4', email: 'emma@example.com', firstName: 'Emma', lastName: 'Wilson', role: 'user', createdAt: '2026-02-15' },
    productId: '3',
    rating: 5,
    title: 'Pure and effective',
    comment: 'You can\'t go wrong with pure creatine. This mixes easily and I\'ve seen great strength gains over the past month. No bloating, no stomach issues. Just results.',
    isVerified: true,
    createdAt: '2026-08-22',
  },
  {
    id: '5',
    userId: 'user5',
    user: { id: 'user5', email: 'david@example.com', firstName: 'David', lastName: 'Brown', role: 'user', createdAt: '2026-03-01' },
    productId: '4',
    rating: 4,
    title: 'Comprehensive formula',
    comment: 'Great multivitamin with everything I need. I feel more energetic throughout the day and my blood work has improved. Good value for the quality.',
    isVerified: true,
    createdAt: '2026-08-25',
  },
  {
    id: '6',
    userId: 'user6',
    user: { id: 'user6', email: 'lisa@example.com', firstName: 'Lisa', lastName: 'Davis', role: 'user', createdAt: '2026-03-15' },
    productId: '5',
    rating: 4,
    title: 'Great for recovery',
    comment: 'I use this during my long runs and it really helps with endurance. The taste is pleasant and it mixes well. Recovery time has definitely improved.',
    isVerified: true,
    createdAt: '2026-08-28',
  },
  {
    id: '7',
    userId: 'user7',
    user: { id: 'user7', email: 'chris@example.com', firstName: 'Chris', lastName: 'Martinez', role: 'user', createdAt: '2026-04-01' },
    productId: '7',
    rating: 4,
    title: 'Perfect for hard gainers',
    comment: 'Finally a mass gainer that doesn\'t make me feel sick. The taste is great and I\'ve put on 5 lbs of lean mass in 2 months. Mixes well with peanut butter and banana.',
    isVerified: true,
    createdAt: '2026-09-01',
  },
  {
    id: '8',
    userId: 'user8',
    user: { id: 'user8', email: 'anna@example.com', firstName: 'Anna', lastName: 'Taylor', role: 'user', createdAt: '2026-04-15' },
    productId: '8',
    rating: 5,
    title: 'Great before bed',
    comment: 'I love taking this before bed. I wake up feeling less sore and my overnight recovery has improved significantly. The vanilla flavor is delicious with almond milk.',
    isVerified: true,
    createdAt: '2026-09-03',
  },
]

export const mockUser: User = {
  id: 'user1',
  email: 'alex@example.com',
  firstName: 'Alex',
  lastName: 'Strong',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
  role: 'user',
  createdAt: '2026-01-01',
}
